version: "3.5"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    container_name: "test-benchmark-node"
    restart: "always"
    volumes:
      - ".:/app"
      - "/app/node_modules"
